services:
  - type: web
    name: credora-blog
    env: node
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: npm start
    port: 3000
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production